language: go
go: 1.8

script:
  - go test ./...

after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi

# We are not granted to run DynamoDB Local on a computer that is not owned or controlled by us (I don't own and control Travis CI...)
#install:
#  - mkdir /tmp/dynamodb
#  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb

#before_script:
#  - java -Djava.library.path=/tmp/dynamodb/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &
#  # TODO solve java start issues 
#  - sleep 5

before_install:
  - go get github.com/aws/aws-sdk-go
  - go get github.com/gorilla/securecookie
  - go get github.com/gorilla/sessions
